### ISSUE TITLE
May I ask why you chose that license?

### ISSUE THREAD

**Issue by alexeieleusis** [mezoni/binary_declarations#5]
In https://github.com/dart-lang/linter/pull/229 you recommend to look at https://github.com/mezoni/binary_declarations/blob/master/lib/src/expression_evaluator/expression_evaluator.dart but I am afraid that with the chosen license I can't learn anything from it if I intend to use that in the dart linter.

**Comment by mezoni** [comment]
You can use it as your own idea since this code (expression evaluator) does not introduces anything new in the software industry, also because it is just a very small part of this software and also because this code (expression evaluator) is not an essence of this software.

How you imagine that I can prevent you to use `print("Hello World")` even if this code used it this software?

Use it. It's open and free since it is insignificant part of this software.

**Comment by alexeieleusis** [comment]
Thanks :)
